language: python

python:
- "2.7"
- "3.6"
- "3.5"
- "3.4"
- "pypy"
- "pypy3"

cache: pip

before_install:
- curl -O http://hugovk.github.io/test/pixel-tools/testimages.zip
- unzip testimages.zip
- curl -O http://hugovk.github.io/test/pixel-tools/ffmpeg-2.1.3-64bit-static.tar.bz2
- tar jxf ffmpeg-2.1.3-64bit-static.tar.bz2
- sudo cp ffmpeg-2.1.3-64bit-static/ffmpeg /usr/bin
- curl -O http://hugovk.github.io/test/pixel-tools/haarcascade_frontalface_alt.xml
# - sudo add-apt-repository ppa:gijzelaar/opencv2.4 -y
# - sudo apt-get update --allow-unauthenticated
# - sudo apt-get install --allow-unauthenticated libopencv-dev
- if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then sudo apt-get install python-tk; fi

install:
# - pip install -r requirements.txt Don't need numpy or psutil yet

- pip install coverage
- pip install Pillow
- pip install pycodestyle pyflakes

before_script:
- chmod +x *.py

script:
# Tests
- coverage erase
- ./test_pixel_tools.py

# Static analysis
- pyflakes .
- pycodestyle --statistics --count .

after_success:
- pip install coveralls && coveralls

matrix:
  allow_failures:
    - python: "pypy"
    - python: "pypy3"
  fast_finish: true
